<a href="https://colab.research.google.com/github/cristobalroldan/TareaGIO/blob/main/Newton_n3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np 
import math

m = 1000
n = 3
a = np.random.uniform(-100,100, size=(m,n))
np.around(a,2,a)
b = np.random.uniform(-100,100, m)
np.around(b,2,b)

x=[1,1,1] # x fijo
print(x)

[1, 1, 1]


In [2]:
import numpy as np 
import math

m = 1000
n = 3
a = np.random.uniform(-100,100, size=(m,n))
np.around(a,2,a)
b = np.random.uniform(-100,100, m)
np.around(b,2,b)

x=[1,1,1] # x fijo

def f(x): 
    i = 1
    totalsum = np.float128(0.0)
    totalexp = np.float128(0.0)
    aux = np.float128(0.0)
    aux2 = np.float128(0.0)
    while i <= m:
        totalexp = 0
        j = 1
        while j <= n:
            aux = np.float128(((a[i-1][j-1])*x[j-1]) + b[i-1])
            totalexp = np.float128(totalexp) + np.float128(aux)
            j = j + 1
        aux2 = np.float128(np.exp(np.float128(totalexp)))
        #print(aux)
        totalsum = np.float128(totalsum + aux2)
        #print(totalsum)
        i = i + 1
    return np.log(np.float64(totalsum)) #retorna float 64, la salida no es tan grande
f(x)

while 1 :
  a = np.random.uniform(-100,100, size=(m,n))
  np.around(a,2,a)
  b = np.random.uniform(-100,100, m)
  np.around(b,2,b)
  if f(x)>520:
    if f(x)<522:
      print(f(x))
      break




520.7700000000367


In [3]:
def fsinLog(x): 
    i = 1
    totalsum = np.float128(0.0)
    totalexp = np.float128(0.0)
    aux = np.float128(0.0)
    aux2 = np.float128(0.0)
    while i <= m:
        totalexp = 0
        j = 1
        while j <= n:
            aux = np.float128(((a[i-1][j-1])*x[j-1]) + b[i-1])
            totalexp = np.float128(totalexp + aux)
            j = j + 1
        aux2 = np.exp(np.float128(totalexp))
        #print(aux)
        totalsum = np.float128(totalsum + aux2)
        #print(totalsum)
        i = i + 1
    return np.float128(totalsum)
fsinLog(x)

1.4707448650616716407e+226

In [4]:
def fdx3(x):
    # print(x)
    i = 1
    totalsum = np.float128(0.0)
    totalexp = np.float128(0.0)
    aux = np.float128(0.0)
    aux2 = np.float128(0.0)
    while i <= m:
        totalexp = 0
        j =1
        while(j <= n):
          aux = a[i-1][j-1]*x[j-1] + b[i-1]
          totalexp = np.float128(totalexp) + np.float128(aux)
          j = j+1
        aux2 = np.float128(np.exp(np.float128(totalexp))*a.item(i-1,0))
        #print(aux2)
        totalsum = np.float128(totalsum) + np.float128(aux2)
        # print(totalsum)
        i = i + 1
    
    i = 1
    totalsum2 = np.float128(0.0)
    totalexp = np.float128(0.0)
    aux = np.float128(0.0)
    aux2 = np.float128(0.0)
    while i <= m:
        totalexp = 0
        j =1
        while(j <= n):
          aux = a[i-1][j-1]*x[j-1] + b[i-1]
          totalexp = np.float128(totalexp) + np.float128(aux)
          j = j +1
        aux2 = np.float128(np.exp(np.float128(totalexp))*a.item(i-1,1))
        #print(aux2)

        totalsum2 = np.float128(totalsum2) + np.float128(aux2)
        # print(totalsum)
        i = i + 1
      
    i = 1
    totalsum3 = np.float128(0.0)
    totalexp = np.float128(0.0)
    aux = np.float128(0.0)
    aux2 = np.float128(0.0)
    while i <= m:
        totalexp = 0
        j =1
        while(j <= n):
          aux = a[i-1][j-1]*x[j-1] + b[i-1]
          totalexp = np.float128(totalexp) + np.float128(aux)
          j = j +1
        aux2 = np.float128(np.exp(np.float128(totalexp))*a.item(i-1,2))
        #print(aux2)

        totalsum3 = np.float128(totalsum3) + np.float128(aux2)
        # print(totalsum)
        i = i + 1

    return np.array( [(1/fsinLog(x))*totalsum, (1/fsinLog(x))*totalsum2, (1/fsinLog(x))*totalsum3], dtype=float )

print(fdx3(x))

[90.54 97.14 74.37]


In [5]:
def Hessian3(x0,fdx3):
  dt=1e-8
  x1x1= ( fdx3( [ x0[0]+dt , x0[1], x0[2] ] )[0] - fdx3(x0)[0] ) / dt
  x1x2= ( fdx3( [ x0[0]+dt , x0[1], x0[2] ] )[1] - fdx3(x0)[1] ) / dt
  x1x3= ( fdx3( [ x0[0]+dt , x0[1], x0[2] ] )[2] - fdx3(x0)[2] ) / dt
  x2x1= ( fdx3( [ x0[0] , x0[1]+dt, x0[2] ] )[0] - fdx3(x0)[0] ) / dt
  x2x2= ( fdx3( [ x0[0] , x0[1]+dt, x0[2] ] )[1] - fdx3(x0)[1] ) / dt
  x2x3= ( fdx3( [ x0[0] , x0[1]+dt, x0[2] ] )[2] - fdx3(x0)[2] ) / dt
  x3x1= ( fdx3( [ x0[0] , x0[1], x0[2]+dt ] )[0] - fdx3(x0)[0] ) / dt
  x3x2= ( fdx3( [ x0[0] , x0[1], x0[2]+dt ] )[1] - fdx3(x0)[1] ) / dt
  x3x3= ( fdx3( [ x0[0] , x0[1], x0[2]+dt ] )[2] - fdx3(x0)[2] ) / dt
  return np.array( [[x1x1, x1x2, x1x3], [x2x1, x2x2, x2x3], [x3x1, x3x2, x3x3]])


print( Hessian3([1,1,1], fdx3 ) )

[[1.42108547e-06 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]]


In [13]:
def backtrack5(x0, f, dltx, t = 1, alpha = 1e-8, beta = 0.25): 
    
    point = x0 
    while f(point-np.dot(t,-dltx)) > f(point)+ alpha*t*(np.dot(np.transpose(-dltx),1*dltx)):
      t *= beta
    return t

In [7]:
def backtrack4(x0, f, fdx3, t = 1, alpha = 1e-8, beta = 0.25):
    
    point = x0 #Necessary to ensure matrix form
    #print(point)
    it=0
    #while f(point - np.dot(t,fdx(point))) > f(point) + alpha * t * np.asscalar(np.dot(np.transpose(fdx(point)), -1*fdx(point))):
    while f(point - np.dot(t,fdx3(point))) > f(point) + alpha * t * (np.dot(np.transpose(fdx3(point)), -1*fdx3(point))):
         t *= beta
         #print(f(point - np.dot(t,fdx(point))),f(point) + alpha * t * (np.dot(np.transpose(fdx(point)), -1*fdx(point))),it)
         it=it+1
    return t

backtrack4([1,1,1], f, fdx3)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:26: RuntimeWarning: overflow encountered in exp


0.015625

In [14]:
import numpy.linalg as npla
##################################################
x=[1,1,1]  #Método de newton siempre parte de [1,1]
######################################################

def lambda_sq(fdx, Hessian, point):
    lambda_sq1 = np.dot(fdx(point).T, np.dot(npla.pinv( Hessian(point,fdx) ) , fdx(point)  )) 
    return lambda_sq1.item() 
     
def delta_x(fdx, Hessian, point):
    delta_x =- np.dot(npla.pinv(Hessian(point,fdx)) , fdx(point))
    return np.array(delta_x)

#eps is the tolerance condition to exit out of the while loop
def newtons_method3(x, eps=0.0001, max_iters=20):
    iters = 1
    lmb_sq = lambda_sq(fdx3, Hessian3, x)
    #In while loop we are checking the magnitude of Newton's decrement. If it's below tolerance we exit out.
    #t=0.0001
    print(x, f(x), fdx3(x), 0, lmb_sq, iters)
    while(( ((lmb_sq))/2.0) > eps):
        dlt_x = delta_x(fdx3, Hessian3, x) # paso
        lmb_sq = lambda_sq(fdx3, Hessian3, x)  #decremento
        t =  backtrack5(x, f, dlt_x)  # t óptimo
        #t = 0.000001*backtrack4(x, f, fdx3)  # t óptimo
        x = np.array((x + np.dot(t , dlt_x))) # nuevo x

        print(x, f(x), fdx3(x), t, lmb_sq, iters)
        iters = 1 + iters  
        if(iters > max_iters):
            break
    return x, f(x), iters
#Test
newtons_method3(x)

[1, 1, 1] 520.7700000000367 [90.54 97.14 74.37] 0 5768471892.785027 1


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:26: RuntimeWarning: overflow encountered in exp


[0.05061929 1.         1.        ] 452.36594562112435 [46.74000098 93.96000005 91.37999959] 1.4901161193847656e-08 5768471892.785027 1
[ 0.0944901  -0.18266064  0.68150714] 374.0380792103897 [ 75.10999999 -48.48        91.79      ] 1.4901161193847656e-08 9272844433.705122 2
[ 0.0944901  -0.18266064  0.68150714] 374.0380792103897 [ 75.10999999 -48.48        91.79      ] 1 0.0 3


(array([ 0.0944901 , -0.18266064,  0.68150714]), 374.0380792103897, 4)