<a href="https://colab.research.google.com/github/cristobalroldan/TareaGIO/blob/main/Newton_n3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [52]:
import numpy as np 
import math

m = 1000
n = 3
a = np.random.uniform(-100,100, size=(m,n))
np.around(a,2,a)
b = np.random.uniform(-100,100, m)
np.around(b,2,b)

x=[1,1,1] # x fijo
print(x)

[1, 1, 1]


In [53]:
def f(x): 
    i = 1
    totalsum = np.float128(0.0)
    totalexp = np.float128(0.0)
    aux = np.float128(0.0)
    aux2 = np.float128(0.0)
    while i <= m:
        totalexp = 0
        j = 1
        while j <= n:
            aux = np.float128(((a[i-1][j-1])*x[j-1]) + b[i-1])
            totalexp = np.float128(totalexp) + np.float128(aux)
            j = j + 1
        aux2 = np.float128(np.exp(np.float128(totalexp)))
        #print(aux)
        totalsum = np.float128(totalsum + aux2)
        #print(totalsum)
        i = i + 1
    return np.log(np.float64(totalsum)) #retorna float 64, la salida no es tan grande
f(x)


520.9800000006861

In [54]:
def fsinLog(x): 
    i = 1
    totalsum = np.float128(0.0)
    totalexp = np.float128(0.0)
    aux = np.float128(0.0)
    aux2 = np.float128(0.0)
    while i <= m:
        totalexp = 0
        j = 1
        while j <= n:
            aux = np.float128(((a[i-1][j-1])*x[j-1]) + b[i-1])
            totalexp = np.float128(totalexp + aux)
            j = j + 1
        aux2 = np.exp(np.float128(totalexp))
        #print(aux)
        totalsum = np.float128(totalsum + aux2)
        #print(totalsum)
        i = i + 1
    return np.float128(totalsum)
fsinLog(x)

1.8144256729990416037e+226

In [55]:
def fdx3(x):
    # print(x)
    i = 1
    totalsum = np.float128(0.0)
    totalexp = np.float128(0.0)
    aux = np.float128(0.0)
    aux2 = np.float128(0.0)
    while i <= m:
        totalexp = 0
        j =1
        while(j <= n):
          aux = a[i-1][j-1]*x[j-1] + b[i-1]
          totalexp = np.float128(totalexp) + np.float128(aux)
          j = j+1
        aux2 = np.float128(np.exp(np.float128(totalexp))*a.item(i-1,0))
        #print(aux2)
        totalsum = np.float128(totalsum) + np.float128(aux2)
        # print(totalsum)
        i = i + 1
    
    i = 1
    totalsum2 = np.float128(0.0)
    totalexp = np.float128(0.0)
    aux = np.float128(0.0)
    aux2 = np.float128(0.0)
    while i <= m:
        totalexp = 0
        j =1
        while(j <= n):
          aux = a[i-1][j-1]*x[j-1] + b[i-1]
          totalexp = np.float128(totalexp) + np.float128(aux)
          j = j +1
        aux2 = np.float128(np.exp(np.float128(totalexp))*a.item(i-1,1))
        #print(aux2)

        totalsum2 = np.float128(totalsum2) + np.float128(aux2)
        # print(totalsum)
        i = i + 1
      
    i = 1
    totalsum3 = np.float128(0.0)
    totalexp = np.float128(0.0)
    aux = np.float128(0.0)
    aux2 = np.float128(0.0)
    while i <= m:
        totalexp = 0
        j =1
        while(j <= n):
          aux = a[i-1][j-1]*x[j-1] + b[i-1]
          totalexp = np.float128(totalexp) + np.float128(aux)
          j = j +1
        aux2 = np.float128(np.exp(np.float128(totalexp))*a.item(i-1,2))
        #print(aux2)

        totalsum3 = np.float128(totalsum3) + np.float128(aux2)
        # print(totalsum)
        i = i + 1

    return np.array( [(1/fsinLog(x))*totalsum, (1/fsinLog(x))*totalsum2, (1/fsinLog(x))*totalsum3], dtype=float )

print(fdx3(x))

[28.49000003 95.71999997 99.91999998]


In [56]:
def Hessian3(x0,fdx3):
  dt=1e-8
  x1x1= ( fdx3( [ x0[0]+dt , x0[1], x0[2] ] )[0] - fdx3(x0)[0] ) / dt
  x1x2= ( fdx3( [ x0[0]+dt , x0[1], x0[2] ] )[1] - fdx3(x0)[1] ) / dt
  x1x3= ( fdx3( [ x0[0]+dt , x0[1], x0[2] ] )[2] - fdx3(x0)[2] ) / dt
  x2x1= ( fdx3( [ x0[0] , x0[1]+dt, x0[2] ] )[0] - fdx3(x0)[0] ) / dt
  x2x2= ( fdx3( [ x0[0] , x0[1]+dt, x0[2] ] )[1] - fdx3(x0)[1] ) / dt
  x2x3= ( fdx3( [ x0[0] , x0[1]+dt, x0[2] ] )[2] - fdx3(x0)[2] ) / dt
  x3x1= ( fdx3( [ x0[0] , x0[1], x0[2]+dt ] )[0] - fdx3(x0)[0] ) / dt
  x3x2= ( fdx3( [ x0[0] , x0[1], x0[2]+dt ] )[1] - fdx3(x0)[1] ) / dt
  x3x3= ( fdx3( [ x0[0] , x0[1], x0[2]+dt ] )[2] - fdx3(x0)[2] ) / dt
  return np.array( [[x1x1, x1x2, x1x3], [x2x1, x2x2, x2x3], [x3x1, x3x2, x3x3]])


print( Hessian3([1,1,1], fdx3 ) )

[[ 1.42108547e-06 -1.42108547e-06  0.00000000e+00]
 [-1.06581410e-06  1.42108547e-06  1.42108547e-06]
 [-1.06581410e-06  1.42108547e-06  1.42108547e-06]]


In [57]:
def backtrack5(x0, f, dltx, t = 1, alpha = 1e-7, beta = 0.5): 
    
    point = x0 
    while f(point-np.dot(t,-dltx)) > f(point)+ alpha*t*(np.dot(np.transpose(-dltx),1*dltx)):
      t *= beta
    return t

In [58]:
def backtrack4(x0, f, fdx3, t = 1, alpha = 1e-8, beta = 0.25):
    
    point = x0 #Necessary to ensure matrix form
    #print(point)
    it=0
    #while f(point - np.dot(t,fdx(point))) > f(point) + alpha * t * np.asscalar(np.dot(np.transpose(fdx(point)), -1*fdx(point))):
    while f(point - np.dot(t,fdx3(point))) > f(point) + alpha * t * (np.dot(np.transpose(fdx3(point)), -1*fdx3(point))):
         t *= beta
         #print(f(point - np.dot(t,fdx(point))),f(point) + alpha * t * (np.dot(np.transpose(fdx(point)), -1*fdx(point))),it)
         it=it+1
    return t

backtrack4([1,1,1], f, fdx3)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:14: RuntimeWarning: overflow encountered in exp
  


0.015625

In [65]:
import numpy.linalg as npla
##################################################
x=[1,1,1]  #Método de newton siempre parte de [1,1]
######################################################

def lambda_sq(fdx, Hessian, point):
    lambda_sq1 = np.dot(fdx(point).T, np.dot(npla.pinv( Hessian(point,fdx) ) , fdx(point)  )) 
    return lambda_sq1.item() 
     
def delta_x(fdx, Hessian, point):
    delta_x =- np.dot(npla.pinv(Hessian(point,fdx)) , fdx(point))
    return np.array(delta_x)

#eps is the tolerance condition to exit out of the while loop
def newtons_method3(x, eps=0.0001, max_iters=20):
    iters = 1
    lmb_sq = lambda_sq(fdx3, Hessian3, x)
    #In while loop we are checking the magnitude of Newton's decrement. If it's below tolerance we exit out.
    #t=0.0001
    print(x, f(x), fdx3(x), 0, iters)
    while(( ((lmb_sq))**2/2.0) > eps):
        dlt_x = delta_x(fdx3, Hessian3, x) # paso
        lmb_sq = lambda_sq(fdx3, Hessian3, x)  #decremento
        t =  backtrack5(x, f, dlt_x)  # t óptimo
        #t = 0.000001*backtrack4(x, f, fdx3)  # t óptimo
        x = np.array((x + np.dot(t , dlt_x))) # nuevo x

        print(x, f(x), fdx3(x), t, lmb_sq, iters)
        iters = 1 + iters  
        if(iters > max_iters):
            break
    return x, f(x), iters
#Test
newtons_method3(x)

[1, 1, 1] 520.9800000006861 [28.49000003 95.71999997 99.91999998] 0 1


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:14: RuntimeWarning: overflow encountered in exp
  


[ 0.38923308  0.98671168 -1.49622096] 461.3671506733936 [-23.85664691  38.04381646 -89.21703544] 2.9802322387695312e-08 8995778994.620335 1
[-0.70359619  0.72495352 -0.30346379] 410.2138880335188 [-98.8002761   92.20717333  59.36942432] 0.00048828125 184937.05509110572 2
[-0.47334096 -0.14765539 -0.0527055 ] 335.52346857147427 [-59.35726199 -78.76577139  66.67869801] 7.450580596923828e-09 11854472950.810867 3
[-0.06441213  0.00062826  0.03703645] 305.65734583427144 [-59.64093237 -67.23939716  64.96642197] 3.0517578125e-05 982014.1991813112 4
[-0.01324158 -0.00301491 -0.00744631] 301.3848835032432 [-19.48944846   7.41398648 -36.70334116] 0.03125 182.29699503006114 5
[0.01338115 0.00605307 0.01295935] 301.13004177010606 [23.27947118 29.58055625 18.19795336] 1 1.2005883793399477 6
[3.99940904e-03 6.56871319e-05 1.03974130e-02] 300.922505208115 [-3.59946961 -4.45572698 11.13540009] 1 0.442134133447452 7
[0.00390098 0.00064495 0.00777925] 300.90697598092146 [-0.16857832 -0.10988762 -0.17702

(array([0.00398757, 0.00067165, 0.00785015]), 300.9069609691391, 10)